language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make catch

branches:
  only:
    - master
    - dev

notifications:
  recipients:
    - hugombarreto@gmail.com
  email:
    on_success: change
    on_failure: always

