language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
install: make
branches:
  only:
    - mkdir build
    - cd build
    - cmake ..
    - make
notifications:
  recipients:
    - hugombarreto@gmail.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
